Repository ai-dynamo/aiperf, pull requests merged in 2025-10, with the labels that each got.

#323 feat: support - vs _ in CaseInsensitiveStrEnum
  aiperf/common/enums/base_enums.py
  tests/common/enums/test_base_enums.py
Labels: feat

#324 feat: add X-Request-Id and X-Correlation-Id headers for traceability
  aiperf/clients/openai/openai_aiohttp.py
  aiperf/common/messages/__init__.py
  aiperf/common/messages/credit_messages.py
  aiperf/common/messages/inference_messages.py
  aiperf/common/models/record_models.py
  aiperf/common/protocols.py
  aiperf/records/record_processor_service.py
  aiperf/workers/worker.py
  tests/clients/openai/test_openai_aiohttp.py
  tests/timing_manager/test_request_rate_strategy.py
  tests/workers/test_worker.py
Labels: feat

#326 fix: Revert "feat: support - vs _ in CaseInsensitiveStrEnum (#323)"
  aiperf/common/enums/base_enums.py
  tests/common/enums/test_base_enums.py
Labels: fix

#311 feat: Add Goodput Metric
  aiperf/common/config/__init__.py
  aiperf/common/config/config_defaults.py
  aiperf/common/config/config_validators.py
  aiperf/common/config/input_config.py
  aiperf/common/constants.py
  aiperf/common/enums/metric_enums.py
  aiperf/metrics/types/good_request_count_metric.py
  aiperf/metrics/types/goodput_metric.py
  aiperf/post_processors/base_metrics_processor.py
  tests/config/test_config_validators.py
  tests/config/test_input_config.py
  tests/metrics/test_good_request_count_metric.py
  tests/metrics/test_goodput_metric.py
  tests/post_processors/test_base_metrics_processor.py
Labels: feat

#316 feat: GPU Telemetry Integration - Milestone 2
  aiperf/common/config/user_config.py
  aiperf/common/messages/telemetry_messages.py
  aiperf/common/models/__init__.py
  aiperf/common/models/telemetry_models.py
  aiperf/controller/system_controller.py
  aiperf/exporters/__init__.py
  aiperf/exporters/csv_exporter.py
  aiperf/exporters/display_units_utils.py
  aiperf/exporters/gpu_telemetry_console_exporter.py
  aiperf/exporters/json_exporter.py
  aiperf/gpu_telemetry/constants.py
  aiperf/gpu_telemetry/telemetry_data_collector.py
  aiperf/gpu_telemetry/telemetry_manager.py
  aiperf/metrics/base_telemetry_metric.py
  aiperf/metrics/gpu_telemetry_types/energy_consumption_metric.py
  aiperf/metrics/gpu_telemetry_types/gpu_memory_used_metric.py
  aiperf/metrics/gpu_telemetry_types/gpu_power_usage_metric.py
  aiperf/metrics/gpu_telemetry_types/gpu_temperature_metric.py
  aiperf/metrics/gpu_telemetry_types/gpu_utilization_metric.py
  aiperf/metrics/gpu_telemetry_types/memory_clock_frequency_metric.py
  aiperf/metrics/gpu_telemetry_types/memory_copy_utilization_metric.py
  aiperf/metrics/gpu_telemetry_types/memory_temperature_metric.py
  aiperf/metrics/gpu_telemetry_types/power_violation_metric.py
  aiperf/metrics/gpu_telemetry_types/sm_clock_frequency_metric.py
  aiperf/metrics/gpu_telemetry_types/thermal_violation_metric.py
  aiperf/metrics/gpu_telemetry_types/xid_errors_metric.py
  aiperf/post_processors/telemetry_results_processor.py
  aiperf/records/records_manager.py
  tests/data_exporters/conftest.py
  tests/data_exporters/test_csv_exporter.py
  tests/data_exporters/test_gpu_telemetry_console_exporter.py
  tests/data_exporters/test_json_exporter.py
  tests/gpu_telemetry/conftest.py
  tests/gpu_telemetry/test_telemetry_data_collector.py
  tests/gpu_telemetry/test_telemetry_metrics.py
  tests/gpu_telemetry/test_telemetry_models.py
  tests/post_processors/test_telemetry_results_processor.py
  tests/records/test_records_filtering.py
Labels: feat

#322 feat: mixed isl/osl distributions
  README.md
  aiperf/common/config/__init__.py
  aiperf/common/config/prompt_config.py
  aiperf/common/models/__init__.py
  aiperf/common/models/sequence_distribution.py
  aiperf/dataset/composer/base.py
  aiperf/dataset/composer/synthetic.py
  docs/tutorials/sequence-distributions.md
  mkdocs.yml
  tests/composers/test_base_composer.py
  tests/composers/test_synthetic_composer.py
  tests/config/test_prompt_config.py
  tests/test_sequence_distribution.py
Labels: feat

#330 chore: remove pandas now that we use numpy only
  aiperf/common/enums/metric_enums.py
  pyproject.toml
Labels: chore

#332 feat: add user documentation for gpu telemetry feature
  docs/tutorials/gpu-telemetry.md
Labels: feat
