Repository ai-dynamo/aiperf, pull requests merged in 2025-09, with the labels that each got.

#277 chore: update README.md to use pip install aiperf
  README.md
Labels: chore

#280 docs: update known issues based on release notes
  README.md
Labels: docs

#275 test: add code coverage reporting
  .github/workflows/run-unit-tests.yml
  Makefile
  tools/generate_api_md.py
Labels: test

#282 fix: ability to limit http connections and pull concurrency
  aiperf/clients/http/defaults.py
  aiperf/common/constants.py
  aiperf/workers/worker.py
  tests/clients/http/test_tcp_connector.py
Labels: fix

#278 docs: add initial feature comparisons with genai-perf
  docs/genai-perf-feature-comparison.md
  docs/migrating.md
Labels: docs

#288 fix: add ruff to mkinit dependencies
  Makefile
Labels: fix

#286 fix: readme invalid command
  README.md
Labels: fix

#290 fix: Add run on main branch
  .github/workflows/run-unit-tests.yml
Labels: fix

#274 feat: GPU Telemetry Milestone 1
  aiperf/common/enums/message_enums.py
  aiperf/common/enums/metric_enums.py
  aiperf/common/enums/post_processor_enums.py
  aiperf/common/enums/service_enums.py
  aiperf/common/messages/__init__.py
  aiperf/common/messages/telemetry_messages.py
  aiperf/common/models/__init__.py
  aiperf/common/models/telemetry_models.py
  aiperf/common/protocols.py
  aiperf/controller/system_controller.py
  aiperf/gpu_telemetry/constants.py
  aiperf/gpu_telemetry/telemetry_data_collector.py
  aiperf/gpu_telemetry/telemetry_manager.py
  aiperf/metrics/__init__.py
  aiperf/metrics/base_metric.py
  aiperf/metrics/base_telemetry_metric.py
  aiperf/metrics/gpu_telemetry_types/energy_consumption_metric.py
  aiperf/metrics/gpu_telemetry_types/gpu_memory_used_metric.py
  aiperf/metrics/gpu_telemetry_types/gpu_power_limit_metric.py
  aiperf/metrics/gpu_telemetry_types/gpu_power_usage_metric.py
  aiperf/metrics/gpu_telemetry_types/gpu_temperature_metric.py
  aiperf/metrics/gpu_telemetry_types/gpu_utilization_metric.py
  aiperf/metrics/gpu_telemetry_types/memory_clock_frequency_metric.py
  aiperf/metrics/gpu_telemetry_types/memory_temperature_metric.py
  aiperf/metrics/gpu_telemetry_types/sm_clock_frequency_metric.py
  aiperf/metrics/gpu_telemetry_types/total_gpu_memory_metric.py
  aiperf/post_processors/telemetry_results_processor.py
  aiperf/records/records_manager.py
  pyproject.toml
  tests/gpu_telemetry/__init__.py
  tests/gpu_telemetry/conftest.py
  tests/gpu_telemetry/test_telemetry_data_collector.py
  tests/gpu_telemetry/test_telemetry_integration.py
  tests/gpu_telemetry/test_telemetry_metrics.py
  tests/gpu_telemetry/test_telemetry_models.py
Labels: feat

#293 feat: add inter-chunk-latency metric using raw value list
  aiperf/common/enums/metric_enums.py
  aiperf/metrics/metric_dicts.py
  aiperf/metrics/types/inter_chunk_latency_metric.py
  aiperf/post_processors/metric_results_processor.py
  tests/metrics/test_inter_chunk_latency_metric.py
  tests/metrics/test_metric_array.py
Labels: feat

#296 chore: Add codecov badge
  README.md
Labels: chore

#298 chore: Add deepwiki badge
  README.md
Labels: chore

#301 feat: show median in console output
  aiperf/exporters/console_metrics_exporter.py
  aiperf/ui/dashboard/realtime_metrics_dashboard.py
  tests/data_exporters/test_console_exporter.py
Labels: feat

#297 docs: Standardize custom dataset type naming convention in CLI
  aiperf/common/config/input_config.py
  docs/benchmark_datasets.md
  docs/cli_options.md
  docs/genai-perf-feature-comparison.md
Labels: docs

#304 fix: avoid PytestCollectionWarning due to TestRunner naming
  tests/ci/test_docs_end_to_end/main.py
  tests/ci/test_docs_end_to_end/test_runner.py
Labels: fix

#307 test: set random seed for image test to fix sporadic errors
  tests/generators/test_image_generator.py
Labels: test

#306 docs: remove --fixed-schedule known issue
  README.md
Labels: docs

#294 fix: Ensure CSV export logic parses correctly
  aiperf/exporters/csv_exporter.py
  tests/clients/http/test_sse_utils.py
  tests/data_exporters/test_csv_exporter.py
Labels: fix
